
name: Train, Test & Deploy Model
on:
  workflow_dispatch:
      why:
        description: 'Why are you running'
        required: false
        default: 'Testing Workflow'    
  pull_request:
#  push:
#    paths:
#    - '.github/workflows/build-model.yml'

jobs:
  training:
    name: Train Model
    runs-on: ubuntu-latest

    env:
      RASA_VERSION: 2.7.1-spacy-en
      RUN_TRAINING: false

    steps:
      - uses: actions/checkout@v1
      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: Did Training Data Change
        if: |
            contains(  steps.files.outputs.all, 'data/' )
            || contains(  steps.files.outputs.all, 'config.yml' )
            || contains(  steps.files.outputs.all, 'domain.yml' )
            || contains(  steps.files.outputs.all, '.github/workflows/build-model.yml' )
        run: echo "RUN_TRAINING=true" >> $GITHUB_ENV
      - name: Rasa Train
        if: env.RUN_TRAINING == 'true'
        uses: RasaHQ/rasa-train-test-gha@main
        with:
          rasa_version: ${{ env.RASA_VERSION }}
          rasa_test: false
          data_validate: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

  test-model:
    name: Test Model
    runs-on: ubuntu-latest
    needs: [training]

    env:
      RASA_VERSION: 2.7.1-spacy-en

    steps:
      - uses: actions/checkout@v1
      - name: Rasa Test
        if: ${{ env.RUN_TRAINING }} == 'true'
        uses: RasaHQ/rasa-train-test-gha@main
        with:
          rasa_version: ${{ env.RASA_VERSION }}
          rasa_train: false
          test_type: all
          data_validate: true
          cross_validation: true
          publish_summary: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload model
        if: ${{ env.RUN_TRAINING }} == 'true'
        uses: actions/upload-artifact@master
        with:
          name: model
          path: models/
